[build]
builder = "NIXPACKS"
buildCommand = "cd bot && pip install -r requirements.txt"

[deploy]
startCommand = "cd bot && python CodeX.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
